# Generated by Django 6.0.4 on 2026-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('unknown', 'Unknown')], default='unknown', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
